### alias

alias g="git"
alias gc="git clone"
alias gs="git status"
alias gb="git branch"
alias gct="git commit"
alias ga="git add"
alias gpom="git push origin main"
alias gact="git add . && git commit"
alias v="nvim"
alias zs="source ~/.zshrc"
alias efl="tail -f /var/log/emerge-fetch.log"
alias c="clear"
alias h="history"
alias sudo="sudo "
alias ln="lanb"
alias rm="wrm"
alias rem="remerge"
alias "clang"="clang -O2 -pipe -march=native"
alias "clang++"="clang++ -O2 -pipe -march=native"
alias e="exit"
alias grep="grep --color=auto"
alias less="less -R"
alias la="ls -a --color"
alias ls="ls -s -l -h -G --color"
alias lr="ls --color -Rhls"
alias md="mkdir -pv"
alias rcreboot="openrc-shutdown -r now"
alias rcshutdown="openrc-shutdown -p now"
